spring.application.name=HealthCareHub

server.port=${PORT:8080}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

jwt.secret=5367566859703373367639792F423F452848284D6251655468576D5A71347437
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

